select * 
from shopping_data 
limit (20);

select count(*)
from shopping_data;
--Q1 What is the total revenue of generated by male vs female customer ?
select gender, SUM(purchase_amount) as revenue
from shopping_data
group by gender
-- Q2 Which customer used a discount but still spend more than the average purchase amount?
select customer_id , purchase_amount 
from shopping_data 
where discount_applied = 'yes' and purchase_amount >= (select AVG(purchase_amount) from shopping_data);

-- Q3 Which are the top five product with the highest average review rating?
SELECT 
    item_purchased AS product,
    ROUND(AVG(review_rating), 2) AS avg_review_rating
FROM shopping_data
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;
-- Q4 Compare the average purchase amounts between Standard and Express shopping?
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM shopping_data
WHERE LOWER(shipping_type) IN ('standard', 'express')
GROUP BY shipping_type;
-- Q5 Do subscribed customer spend more Compare? average spend and total revenue between subscribers and non subscribers?

